#!/bin/csh

# USERS MUST CHANGE THESE !!!!!!
set SWIFT_DIR=/home/hal/SWIFT
set FORTRAN=ifort
#set FFLAGS='-O -recursive'
set FFLAGS='-O -recursive -fpe0 -traceback'

foreach file (*.f)
    echo $file | set file2=`awk -F"." '{print$1}'`
    echo $file
    $FORTRAN  $FFLAGS -o  $file2 $file -L$SWIFT_DIR -lswift -lfxdr -lnumrec -lastro -lMT_rand
end

rm *.o
