#!/bin/csh

# USERS MUST CHANGE THESE !!!!!!
set SWIFT_DIR=/home/hal/SWIFT
set FORTRAN=ifort
#set FFLAGS='-O -recursive -c'
set FFLAGS='-O -recursive -fpe0 -traceback -c'
set PRECOMP=/usr/bin/cpp
set CPPFLAGS='-traditional -D_OPEN_POSITION -U_RECUR_SUB -D_FXDR_AVAIL'

# To Profile the code:
#set FFLAGS='-G -c'

if (`ls *.F | wc -l` != 0 ) then
    echo Doing precompiler
    foreach file (*.F)
        echo $file | set file2=`awk -F"." '{print$1}'`
        echo $PRECOMP $CPPFLAGS "$file2".F "$file2"_CPP.f
        $PRECOMP $CPPFLAGS "$file2".F "$file2"_CPP.f
     end
else
    echo No need to precompile
endif

echo Doing Fortran
foreach file (*.f)
    echo $file | set file2=`awk -F"." '{print$1}'`
    echo $file2
    $FORTRAN $FFLAGS "$file2".f
    ar vr $SWIFT_DIR/libswift.a  "$file2".o
end

rm *.o
rm *CPP.f
echo Done directory $PWD

